### ISSUE TITLE
Add dump data

### ISSUE THREAD

**Issue by dianatatu** [ami-lab/AmI-Platform#237]
### Need

We need to have a reliable dump data for the pipeline tests
### Deliverables
- [ ] `andrei.txt`
- [ ] `diana.txt`
- [ ] `all.txt`
- [ ] `all_rgb_only.txt`
### TODOs
- [ ] provide all the above-mentioned list of dump files
- [ ] remove the old ones
